# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/geka',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/geka',
                'lib_path': 'geka'},
  'syms': {'geka.core': {'geka.core.foo': ('core.html#foo', 'geka/core.py')}}}
