# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/geka',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/geka',
                'lib_path': 'geka'},
  'syms': { 'geka.loading': { 'geka.loading.download': ('loading.html#download', 'geka/loading.py'),
                              'geka.loading.load_ossl': ('loading.html#load_ossl', 'geka/loading.py')}}}
